"""Declarative base, naming conventions, and shared column mixins.

Kept separate from `core.database.__init__` (engine/session) so that importing
model definitions never pulls in a database connection - Alembic and the DDL
tests both need the metadata without an engine.
"""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, MetaData, func, text
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Deterministic constraint names. Without this, PostgreSQL auto-names constraints
# and Alembic cannot reliably emit DROP CONSTRAINT in a downgrade. Explicit names
# given at the constraint site (matching docs/backend/DATABASE_CONTRACT.md) win
# over these; the convention is the fallback for anything unnamed.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_name)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class UUIDPrimaryKeyMixin:
    """UUID primary key generated by PostgreSQL.

    `gen_random_uuid()` is built into PostgreSQL 13+; no pgcrypto extension is
    required. See docs/backend/DATABASE_SETUP.md for the version requirement.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )


class TimestampMixin:
    """created_at / updated_at, TIMESTAMPTZ per the contract.

    `updated_at` is maintained by SQLAlchemy's `onupdate` rather than a database
    trigger - one mechanism, visible in the model, no hidden behaviour.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )


class CreatedAtMixin:
    """created_at only - for append-only tables that are never updated in place."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
